version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Google Pub/Sub emulator
  # pubsub:
  #   image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  #   container_name: pubsub_emulator
  #   ports:
  #     - "8085:8085"
  #   command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
  #   networks:
  #     - ct_network
  #   volumes:
  #     - mongodb_data:/data/pubsub

networks:
  ct_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
